version: "3"
services: 
    mymongo_1:
        image: "mongo"
        ports:
            - 27017:27017
    
    auth:
        build: .
        depends_on: 
            - mymongo_1
        ports:
            - "5005:5005"