version: '3.3'
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "5002:8080"
    links:
      - postgres


  postgres:
    # image: "postgres:latest"
    image: "postgis/postgis:latest"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "db_pass"
    ports:
      - "5432:5432"
